version: '2'

services:
  master:
    container_name: 'citus_master'
    image: 'citusdata/citus:6.2.3'
    ports: ['5436:5436']
    labels: ['com.citusdata.role=Master']
    volumes: ['/var/run/postgresql']
  worker:
    image: 'citusdata/citus:6.2.3'
    labels: ['com.citusdata.role=Worker']
  config:
    container_name: 'citus_config'
    image: 'citusdata/workerlist-gen:2.0.0'
    volumes: ['/var/run/docker.sock:/tmp/docker.sock']
    volumes_from: ['master']
